//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiIP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiIP.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Profile.
        /// </summary>
        internal static string btnActivate {
            get {
                return ResourceManager.GetString("btnActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage....
        /// </summary>
        internal static string btnManage {
            get {
                return ResourceManager.GetString("btnManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show detail.
        /// </summary>
        internal static string chkShowDetail {
            get {
                return ResourceManager.GetString("chkShowDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Configuration.
        /// </summary>
        internal static string lblCurrentConfig {
            get {
                return ResourceManager.GetString("lblCurrentConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network &amp;Card:.
        /// </summary>
        internal static string lblNetCard {
            get {
                return ResourceManager.GetString("lblNetCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Profile:.
        /// </summary>
        internal static string lblProfile {
            get {
                return ResourceManager.GetString("lblProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Selected.
        /// </summary>
        internal static string lblProfilSelected {
            get {
                return ResourceManager.GetString("lblProfilSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string tsmiBackup {
            get {
                return ResourceManager.GetString("tsmiBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastest DNS.
        /// </summary>
        internal static string tsmiFastestDNS {
            get {
                return ResourceManager.GetString("tsmiFastestDNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flush DNS.
        /// </summary>
        internal static string tsmiFlushDNS {
            get {
                return ResourceManager.GetString("tsmiFlushDNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string tsmiRestore {
            get {
                return ResourceManager.GetString("tsmiRestore", resourceCulture);
            }
        }
    }
}
